### ISSUE TITLE
Docs website

### ISSUE THREAD

**Issue by codewithcats** [ActorForth/bch-devsuite#18]
Create and deploy docs website for bch-toolkit
- generate from readme
- auto build and deploy using CI

**Comment by codewithcats** [comment]
Here is what I & @merc1er  think we should have in our docs site:

**Getting Started**
- quick way to get start with our tool step by step
- overall concept (not so detailed) about how things work together (with few diagrams)
- (optional) video tutorial

**Advance Usage**
- how to operate in advance use cases, use case by use case

**API (or command) reference**
- explanation of all available options/configurations that can be used

**Architecture**
- deeper details of how things work together

**Sponsorship**
- provide a way to funding us

_less important sections_
**Contribution**
- how to contribute to this project; how to do PR, for example

**Project Roadmap**

**Comment by codewithcats** [comment]
I rearranged sections in our README and merged to `develop` branch (PR #33) 

Documentation writing guideline

- The website will be generated from README.md. You write on the section you responsible for.
- Each h1 (start with #) will be split into different pages. for example, # Getting Started will be getting-started.html
- Each page will have it own menu on the sidebar
- Each h2 (start with ##) will be display as a submenu of its parent page

**Comment by merc1er** [comment]
I’m thinking some info on the minimum and recommended specs to run mainnet would be useful in the docs 😀

**Comment by SuperCipher** [comment]
The website is up can be seen here.
https://docs.actorforth.org/
